services:
  - type: web
    name: kutuphane
    runtime: node
    rootDir: server
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
